version: '3.7'

services:
  servidor:
    image: fjortegan/dwes:laravel
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "80:80"
    volumes:
      - ./laravel:/var/www/html/

  db:
    image: mariadb
    
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql/  
    environment:
      MYSQL_DATABASE: fruteria
      MYSQL_USER: admin
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: pestillo

  phpmyadmin:
    image: phpmyadmin
    
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1